### ISSUE TITLE
Presubmission cleanup checklist

### ISSUE THREAD

**Issue by gumityolcu** [dilyabareeva/quanda#180]
- [x]  no names are left:

- - [x]  in the docs

- - [x]  in the code

- [x]  no TODO left in the codebase

- [x]  docs folder is up to date with latest version of the lib -> recompile the html and upload to the repo!

- [x] re-run the tutorials (NOT demo_prep.ipynb), run `black tutorials/*.ipynb`

Please feel free to add items
